@UBB-SE-2024-923-1_HostAddress = https://localhost:7025

GET {{UBB-SE-2024-923-1_HostAddress}}/addistributiondata

###

POST {{UBB-SE-2024-923-1_HostAddress}}/addistributiondata
Content-Type: application/json

{
  //AdDistributionData
}

###

GET {{UBB-SE-2024-923-1_HostAddress}}/addistributiondata/0+0

###

DELETE {{UBB-SE-2024-923-1_HostAddress}}/addistributiondata/0+0

###

PUT {{UBB-SE-2024-923-1_HostAddress}}/addistributiondata/0+0
Content-Type: application/json

{
  //AdDistributionData
}

###

GET {{UBB-SE-2024-923-1_HostAddress}}/artistdetails

###

POST {{UBB-SE-2024-923-1_HostAddress}}/artistdetails
Content-Type: application/json

{
  //ArtistDetails
}

###

GET {{UBB-SE-2024-923-1_HostAddress}}/artistdetails/0

###

DELETE {{UBB-SE-2024-923-1_HostAddress}}/artistdetails/0

###

PUT {{UBB-SE-2024-923-1_HostAddress}}/artistdetails/0
Content-Type: application/json

{
  //ArtistDetails
}

###

GET {{UBB-SE-2024-923-1_HostAddress}}/songrecommendationsdetails

###

POST {{UBB-SE-2024-923-1_HostAddress}}/songrecommendationsdetails
Content-Type: application/json

{
  //SongRecommendationDetails
}

###

GET {{UBB-SE-2024-923-1_HostAddress}}/songrecommendationsdetails/0+0+0

###

DELETE {{UBB-SE-2024-923-1_HostAddress}}/songrecommendationsdetails/0+0+0

###

PUT {{UBB-SE-2024-923-1_HostAddress}}/songrecommendationsdetails/0+0+0
Content-Type: application/json

{
  //SongRecommendationDetails
}

###
